# Generated by Django 5.2.7 on 2025-11-15 14:41

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0006_alter_subsidy_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('documents_required', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='SubsidyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_status', models.CharField(blank=True, default='Pending', max_length=50, null=True)),
                ('application_id', models.PositiveIntegerField(editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('aadhaar', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('land_area', models.FloatField()),
                ('land_unit', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('ownership', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Under Review', 'Under Review')], default='Pending', max_length=20, null=True)),
                ('documents', models.ManyToManyField(related_name='applications', to='subsidy.document')),
                ('subsidy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.subsidy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subsidy')},
            },
        ),
    ]
