# Generated by Django 5.2.7 on 2025-11-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subsidy',
        ),
    ]
