# Generated by Django 5.2.7 on 2025-11-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyapplication',
            name='subsidy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidy.subsidy'),
        ),
    ]
