# Generated by Django 5.2.7 on 2025-11-15 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0002_delete_subsidy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidyapplication',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subsidy_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subsidyapplication',
            name='officer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsidyapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsidyapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected')], default='Pending', max_length=20, null=True),
        ),
    ]
