# Generated by Django 5.2.7 on 2025-11-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0002_alter_subsidyapplication_subsidy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidyapplication',
            old_name='subsidy',
            new_name='subsidy_id',
        ),
    ]
