# Generated by Django 5.2.7 on 2025-11-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subsidy_created_by'),
        ('subsidy', '0003_rename_subsidy_subsidyapplication_subsidy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidyapplication',
            name='subsidy_id',
        ),
        migrations.AddField(
            model_name='subsidyapplication',
            name='subsidy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='app.subsidy'),
        ),
    ]
