# Generated by Django 5.2.7 on 2025-11-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0003_subsidyapplication_assigned_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyapplication',
            name='application_id',
            field=models.CharField(editable=False, max_length=26, unique=True),
        ),
        migrations.AlterField(
            model_name='subsidyapplication',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Payment done', 'Payment done')], default='Pending', max_length=20, null=True),
        ),
    ]
