# Generated by Django 5.2.7 on 2025-11-13 18:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subsidy_created_by'),
        ('subsidy', '0004_remove_subsidyapplication_subsidy_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('owner', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='subsidyapplication',
            unique_together={('user', 'subsidy')},
        ),
    ]
