# Generated by Django 5.2.7 on 2025-11-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0005_alter_document_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
    ]
