# Generated by Django 5.2.7 on 2025-10-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='documents_required',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
