# Generated by Django 5.2.7 on 2025-11-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subsidy_documents_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, help_text='Subsidy rating out of 5', max_digits=3),
        ),
    ]
