# Generated by Django 5.2.7 on 2025-11-12 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subsidy_rating_subsidyrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this subsidy (subsidy_provider)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subsidies', to=settings.AUTH_USER_MODEL),
        ),
    ]
