# Generated by Django 5.2.7 on 2025-11-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subsidy_rating'),
        ('app', '0004_subsidy_created_by'),
    ]

    operations = [
    ]
