# Generated by Django 5.2.7 on 2025-11-14 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_0003_subsidy_rating_0004_subsidy_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='rating',
            field=models.FloatField(default=0, help_text='Average rating from 0 to 5 stars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
