# Generated by Django 5.2.7 on 2026-05-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_subsidy_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
