# Generated by Django 5.2.7 on 2025-11-13 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=32),
        ),
    ]
