# Generated by Django 5.2.7 on 2025-11-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_grievance_assigned_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='officer_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
