# Generated by Django 5.2.7 on 2025-11-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
