# Generated by Django 5.2.7 on 2026-05-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0004_emailverification_mobileverification_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('email_verify', 'Email Verification'), ('forgot_password', 'Forgot Password')], max_length=20),
        ),
        migrations.DeleteModel(
            name='MobileVerification',
        ),
    ]
