# Generated by Django 5.2.7 on 2025-10-29 17:27

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('bank_passbook', 'Bank Passbook / Cancelled Cheque'), ('scope_certificate', 'Scope Certificate of Organic Farming'), ('annexure_copy', 'Copy of Annexure in Group Certification'), ('residue_fee_receipt', 'Receipt of fee paid for residue testing'), ('divyang_certificate', 'Copy of Divyang Certificate (if applicable)'), ('joint_account_letter', "Joint Account Holder's Construction Letter"), ('residue_testing_copy', 'Copy of residue testing'), ('aadhar_card', 'Aadhar Card'), ('land_document', 'Copy of 7/12 and 8-A')], max_length=50)),
                ('document_number', models.CharField(max_length=50)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
