# Generated by Django 5.2.7 on 2025-10-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_document_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='document',
            name='resource_type',
            field=models.CharField(default='image', max_length=10),
        ),
    ]
