# Generated by Django 5.2.7 on 2025-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_delete_photo_document_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='resource_type',
            field=models.CharField(default='raw', max_length=10),
        ),
    ]
