# Generated by Django 5.2.7 on 2025-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_alter_document_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='resource_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
